In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('filtered_spotify_TH.csv')
df.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,3yDRcs0Y4pPzkvMbUfeF9H,Moonlit Floor,LISA,1,0,0,TH,2024-10-18,87,False,...,5,-3.951,0,0.1120,0.12800,0.000000,0.3100,0.672,109.954,4
1,7tI8dRuH2Yc6RuoTjxo4dU,Who,Jimin,2,0,0,TH,2024-10-18,93,False,...,0,-3.743,0,0.0320,0.00289,0.000000,0.1930,0.838,116.034,4
2,2CspwnypzT7rcWI9RfsoSb,Mantra,JENNIE,3,0,47,TH,2024-10-18,83,True,...,10,-4.984,0,0.0432,0.00434,0.000012,0.0815,0.838,116.988,4
3,2N0SPREDYqILVEFSsWF5N5,Love Me Again,V,4,0,-1,TH,2024-10-18,86,False,...,0,-6.182,0,0.0532,0.18300,0.000001,0.1670,0.363,74.029,4
4,2KslE17cAJNHTsI2MI0jb2,Standing Next to You,Jung Kook,5,0,-1,TH,2024-10-18,89,False,...,2,-4.389,0,0.0955,0.04470,0.000000,0.3390,0.816,106.017,4

In [3]:
temp = pd.read_csv('1023Tto1123T.csv')
temp.head()

         date  average_temp
0  18/10/2023     31.070833
1  19/10/2023     29.104167
2  20/10/2023     30.775000
3  21/10/2023     27.512500
4  22/10/2023     29.141667

In [4]:
rain = pd.read_csv('1023to1024.csv')
rain.tail()

           date  rain
362  14/10/2024   0.0
363  15/10/2024   0.0
364  16/10/2024   0.2
365  17/10/2024   0.2
366  18/10/2024  32.0

In [5]:
environment = pd.merge(temp, rain, on='date', how='inner')

In [6]:
environment.head()

         date  average_temp  rain
0  18/10/2023     31.070833   7.8
1  19/10/2023     29.104167   0.2
2  20/10/2023     30.775000   8.4
3  21/10/2023     27.512500  47.2
4  22/10/2023     29.141667   0.0

In [7]:
columns_to_drop = ['spotify_id', 'daily_movement', 'weekly_movement', 'duration_ms', 'album_release_date', 'key',
                   'mode', 'daily_rank', 'time_signature', 'album_name', 'artists', 'popularity']
df = df.drop(columns=columns_to_drop)

In [8]:
spotify_TH = df[df['country'] == 'TH']

In [9]:
spotify_TH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18261 entries, 0 to 18260
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              18261 non-null  object
 1   country           18261 non-null  object
 2   snapshot_date     18261 non-null  object
 3   is_explicit       18261 non-null  bool
 4   danceability      18261 non-null  float64
 5   energy            18261 non-null  float64
 6   loudness          18261 non-null  float64
 7   speechiness       18261 non-null  float64
 8   acousticness      18261 non-null  float64
 9   instrumentalness  18261 non-null  float64
 10  liveness          18261 non-null  float64
 11  valence           18261 non-null  float64
 12  tempo             18261 non-null  float64
dtypes: bool(1), float64(9), object(3)
memory usage: 1.7+ MB

In [10]:
spotify_TH.head()

,name,country,snapshot_date,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,Moonlit Floor,TH,2024-10-18,False,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954
1,Who,TH,2024-10-18,False,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034
2,Mantra,TH,2024-10-18,True,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988
3,Love Me Again,TH,2024-10-18,False,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029
4,Standing Next to You,TH,2024-10-18,False,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017

In [11]:
spotify_TH['snapshot_date'] = pd.to_datetime(spotify_TH['snapshot_date'], errors='coerce').dt.strftime('%d/%m/%Y')
spotify_TH['snapshot_date'] = spotify_TH['snapshot_date'].fillna('14/10/2024')

In [12]:
spotify_TH.head()

,name,country,snapshot_date,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,Moonlit Floor,TH,18/10/2024,False,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954
1,Who,TH,18/10/2024,False,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034
2,Mantra,TH,18/10/2024,True,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988
3,Love Me Again,TH,18/10/2024,False,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029
4,Standing Next to You,TH,18/10/2024,False,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017

In [13]:
train = spotify_TH.merge(environment, left_on='snapshot_date', right_on='date')

In [14]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3305 entries, 0 to 3304
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              3305 non-null   object
 1   country           3305 non-null   object
 2   snapshot_date     3305 non-null   object
 3   is_explicit       3305 non-null   bool
 4   danceability      3305 non-null   float64
 5   energy            3305 non-null   float64
 6   loudness          3305 non-null   float64
 7   speechiness       3305 non-null   float64
 8   acousticness      3305 non-null   float64
 9   instrumentalness  3305 non-null   float64
 10  liveness          3305 non-null   float64
 11  valence           3305 non-null   float64
 12  tempo             3305 non-null   float64
 13  date              3305 non-null   object
 14  average_temp      3305 non-null   float64
 15  rain              3305 non-null   float64
dtypes: bool(1), float64(11), object(4)
memory usage: 390.7+ KB

In [15]:
train = train.drop(labels=['snapshot_date', 'date', 'country'], axis=1)

In [16]:
train.head()

,name,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,average_temp,rain
0,Moonlit Floor,False,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954,34.022222,32.0
1,Who,False,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034,34.022222,32.0
2,Mantra,True,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988,34.022222,32.0
3,Love Me Again,False,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029,34.022222,32.0
4,Standing Next to You,False,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017,34.022222,32.0

In [17]:
test = (
    spotify_TH
    .drop(labels=['snapshot_date', 'country'], axis=1)  # ลบคอลัมน์ไม่จำเป็น
    .sort_values(by='name')                             # เรียงตามชื่อเพลง
    .drop_duplicates(subset='name')                     # ลบเพลงที่ชื่อซ้ำกัน
)

In [18]:
test.head()

,name,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
2412,28 (feat. NiiHWA),True,0.679,0.645,-7.107,0.0513,0.0897,0.000000,0.1210,0.349,119.934
713,3D (feat. Jack Harlow),True,0.853,0.824,-3.287,0.1030,0.0322,0.000000,0.0859,0.888,108.044
8749,9 นาฬิกา,False,0.571,0.929,-3.405,0.0402,0.3030,0.000000,0.0872,0.628,109.998
15762,Abyss,False,0.434,0.506,-5.359,0.0317,0.5350,0.000000,0.1630,0.346,143.776
15705,Agora Hills,True,0.755,0.687,-6.247,0.1010,0.1830,0.000177,0.1250,0.381,123.010

In [19]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287 entries, 2412 to 9117
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              287 non-null    object
 1   is_explicit       287 non-null    bool
 2   danceability      287 non-null    float64
 3   energy            287 non-null    float64
 4   loudness          287 non-null    float64
 5   speechiness       287 non-null    float64
 6   acousticness      287 non-null    float64
 7   instrumentalness  287 non-null    float64
 8   liveness          287 non-null    float64
 9   valence           287 non-null    float64
 10  tempo             287 non-null    float64
dtypes: bool(1), float64(9), object(1)
memory usage: 24.9+ KB

In [20]:
nameList = list(train.sort_values(by='name')['name'].unique())

In [21]:
nameList

['3D (feat. Jack Harlow)',
 'Agora Hills',
 'All I Want for Christmas Is You',
 'Ay-Yo',
 'B.O.M.B',
 'B.O.M.B - KABOOM ver.',
 'BATTER UP',
 'BIRDS OF A FEATHER',
 'Be Mine',
 'Be There For Me',
 'Because of You, I Shine',
 'Best Thing',
 'Birthday',
 "Blank Space (Taylor's Version)",
 'Chasing That Feeling',
 'Chill Kill',
 'Closer Than This',
 'Closer to You (feat. Major Lazer)',
 'Cruel Summer',
 'DAY ONE',
 'Die With A Smile',
 'Dopamine - GISELLE Solo',
 'Drama',
 'Dreamers [Music from the FIFA World Cup Qatar 2022 Official Soundtrack]',
 'Espresso',
 'FLOWER',
 'FRI(END)S',
 'Fact Check',
 'Golden Hour',
 'Goodbye',
 'Haegeum',
 'Hate You',
 'Highway 1009',
 'How You Like That',
 'I Just Wanna Know',
 'Jingle Bell Rock',
 'LALALALA',
 'LALISA',
 'LIAR',
 'Last Christmas - Single Version',
 'Like Crazy',
 'Loop (ฉันจึงวนกลับมา)',
 'Love Me Again',
 'MONEY',
 'MORE',
 'Mantra',
 'Moonlit Floor',
 'My Love Mine All Mine',
 'New Woman (feat. ROSALÍA)',
 'Nightwalker',
 'No More Dream',
 'One Of The Girls (with JENNIE, Lily Rose Depp)',
 'Paint Me Naked',
 'Paint The Town Red',
 'People Pt.2 (feat. IU)',
 "Please Don't Change (feat. DJ Snake)",
 'Promethazine',
 'Proud',
 "Rockin' Around The Christmas Tree",
 'Rockstar',
 'SHALALA',
 'SPOT!',
 'Santa Tell Me',
 'Seven (feat. Latto) (Explicit Ver.)',
 'Shall We',
 'Shot Glass of Tears',
 'Slow Dancing',
 'Snow Flower (feat. Peakboy)',
 'Snowman',
 'Somebody',
 'Spark - WINTER Solo',
 'Standing Next to You',
 'Style',
 "Style (Taylor's Version)",
 'Summertime',
 'Sunflower - Spider-Man: Into the Spider-Verse',
 'Super Shy',
 'Super Tuna',
 'Supernova',
 'Sweet Venom',
 'TAP',
 'THE GIRLS - BLACKPINK THE GAME OST',
 'TOO MUCH',
 'TRANSFORMER',
 'The Astronaut',
 'The First Snow',
 'Tip Toe',
 'Too Sad to Dance',
 'UP - KARINA Solo',
 'Who',
 'Yes or No',
 'You & Me',
 'You & Me (Coachella ver.)',
 'Yours Ever',
 'double take',
 'greedy',
 'santa doesn’t know you like i do',
 'กลับมาเพื่อบอกลา (JUST TO LET ME KNOW)',
 'กลิ่นดอกไม้',
 'กำแพงหัวใจ',
 'ขอให้เธอใจดี',
 'ข้างกัน (City)',
 'ข้างกาย ( With You )',
 'จดจำ',
 'จังหวะตกหลุมรัก - Magic Moment',
 'จากตรงนี้ที่(เคย)สวยงาม [La La Bye]',
 'จำนน',
 'ฉันคือนักสะสมความเศร้า',
 'ฉันไม่ต้องการตัวเธอในตอนนี้',
 'ซูลูปาก้า ตาปาเฮ้',
 'ซ่อน(ไม่)หา',
 'ดอกไม้ที่รอฝน (spring)',
 'ดาวหางฮัลเลย์',
 'ที่เดิม',
 'บรรยากาศ',
 'ปล่อยดาว',
 'ปล่อยดาว (Flaw)',
 'ผิดตั้งแต่เริ่ม (ชู้รัก)',
 'ผู้ถูกเลือกให้ผิดหวัง (ดอกไม้ฤดูหนาว)',
 'พบรัก',
 'พิจารณา (Consider)',
 'พี่ชอบหนูที่สุดเลย',
 'ฟ้ารักพ่อ (DILF)',
 'ยินดี - เพลงประกอบละครมาตาลดา ช่อง 3',
 'ยิ้มทั้งน้ำตา',
 'ยื้อ',
 'รสหวาน',
 'รักแรก (First Love) [เพลงประกอบภาพยนตร์ รักแรกโคตรลืมยาก My Precious]',
 'ร้องไปกับฟ้า (Original Soundtrack "ภาพยนตร์ 4KINGS II") [feat. D Gerrard]',
 'ลั่นทม (เพลงประกอบละคร "หอมกลิ่นความรัก")',
 'ลั่นทม (เพลงประกอบละคร หอมกลิ่นความรัก)',
 'ลาก่อน',
 'วันที่นาฬิกาของเราหมุนไปพร้อมกัน',
 'วันนี้ปีที่แล้ว',
 'วาสนาผู้ใด',
 'สลักจิต',
 'สาริกาลิ้นทอง (Smooth-talker)',
 'ส่วนต่าง (do it without me)',
 'หากจะเพียงขอ(Sincare)',
 'อยู่ได้แล้ว',
 'อาจเป็นเพราะฉันเอง (me.)',
 'อิจฉา',
 'เจ้าของที่',
 'เดินมาส่ง - BYE',
 'เธอคือกาแฟในตอนเช้า',
 'เธอไม่ได้สอนให้ฉันอยู่คนเดียว',
 'เผื่อวันไหนเธอจะกลับมา',
 'เพลงรักเพลงแรก - Blooming',
 'เพลงรักในวันลา',
 'เวลาเธอยิ้ม',
 'เหมือนวิวาห์ (Rain wedding) [From "วิมานหนาม"]',
 'แค่น้องชาย (brother zone)',
 'แค่ไหนแค่นั้น (NO MATTER WHAT)',
 'แอบหวัง',
 'โต๊ะริม',
 'ใครเพื่อนแก',
 'ใจพัง',
 'ใจลอย',
 'ไม่เปลี่ยนเลย (Best Luck)',
 'ไม่เป็นรอง',
 'ไม่ให้ไป']

In [22]:
train.head()

,name,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,average_temp,rain
0,Moonlit Floor,False,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954,34.022222,32.0
1,Who,False,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034,34.022222,32.0
2,Mantra,True,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988,34.022222,32.0
3,Love Me Again,False,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029,34.022222,32.0
4,Standing Next to You,False,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017,34.022222,32.0

In [23]:
train['is_explicit'] = train['is_explicit'].astype(int)  # False -> 0, True -> 1

In [24]:
train.head()

,name,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,average_temp,rain
0,Moonlit Floor,0,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954,34.022222,32.0
1,Who,0,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034,34.022222,32.0
2,Mantra,1,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988,34.022222,32.0
3,Love Me Again,0,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029,34.022222,32.0
4,Standing Next to You,0,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017,34.022222,32.0

In [25]:
song_names = train['name']  # เก็บชื่อเพลงไว้
X = train.drop(['average_temp', 'rain', 'name'], axis=1)
y = train[['average_temp', 'rain']]

In [26]:
X

,is_explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,0,0.733,0.786,-3.951,0.1120,0.12800,0.000000,0.3100,0.672,109.954
1,0,0.660,0.756,-3.743,0.0320,0.00289,0.000000,0.1930,0.838,116.034
2,1,0.894,0.725,-4.984,0.0432,0.00434,0.000012,0.0815,0.838,116.988
3,0,0.633,0.607,-6.182,0.0532,0.18300,0.000001,0.1670,0.363,74.029
4,0,0.711,0.809,-4.389,0.0955,0.04470,0.000000,0.3390,0.816,106.017
...,...,...,...,...,...,...,...,...,...,...
3300,0,0.578,0.569,-8.811,0.0786,0.44100,0.008830,0.1120,0.734,168.132
3301,0,0.433,0.400,-9.414,0.0311,0.92900,0.000000,0.1050,0.324,171.892
3302,0,0.573,0.874,-4.859,0.0271,0.10100,0.000000,0.0798,0.571,101.976
3303,0,0.361,0.485,-10.081,0.0387,0.41200,0.022300,0.2640,0.242,173.395
3304,0,0.563,0.852,-7.114,0.0319,0.01750,0.001350,0.1080,0.764,135.012

In [27]:
y

      average_temp  rain
0        34.022222  32.0
1        34.022222  32.0
2        34.022222  32.0
3        34.022222  32.0
4        34.022222  32.0
...            ...   ...
3300     31.070833   7.8
3301     31.070833   7.8
3302     31.070833   7.8
3303     31.070833   7.8
3304     31.070833   7.8

[3305 rows x 2 columns]

In [28]:
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultiOutputRegressor(RandomForestRegressor(n_estimators=100, random_state=42))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

X_result = X_test.reset_index(drop=True)
y_result = pd.DataFrame(y_pred, columns=['average_temp', 'rain'])

rounded_pred = np.round(y_pred)
rounded_true = np.round(y_test.to_numpy())

temp_acc = accuracy_score(rounded_true[:, 0], rounded_pred[:, 0])
rain_acc = accuracy_score(rounded_true[:, 1], rounded_pred[:, 1])

accuracy = (temp_acc + rain_acc) / 2

X_result.head(), y_result.head(), accuracy

(   is_explicit  danceability  energy  loudness  speechiness  acousticness  \
 0            1         0.894   0.725    -4.984       0.0432       0.00434
 1            0         0.631   0.822    -4.793       0.0269       0.21300
 2            0         0.770   0.677    -6.427       0.0589       0.52600
 3            0         0.711   0.809    -4.389       0.0955       0.04470
 4            0         0.633   0.607    -6.182       0.0532       0.18300

    instrumentalness  liveness  valence    tempo
 0          0.000012    0.0815    0.838  116.988
 1          0.001010    0.2120    0.879  149.886
 2          0.000483    0.1280    0.942  135.982
 3          0.000000    0.3390    0.816  106.017
 4          0.000001    0.1670    0.363   74.029  ,
    average_temp       rain
 0     33.503510  15.039359
 1     28.568992   1.630439
 2     28.512308   1.589733
 3     28.801291   1.109780
 4     28.410122   1.166777,
 0.23751891074130105)

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

param_grid = {
    'estimator__n_estimators': [50, 100, 200],
    'estimator__max_depth': [None, 10, 20],
    'estimator__min_samples_split': [2, 5],
}

base_model = RandomForestRegressor(random_state=42)
multioutput_model = MultiOutputRegressor(base_model)

grid_search = GridSearchCV(
    estimator=multioutput_model,
    param_grid=param_grid,
    scoring='r2',
    cv=3,
    verbose=1,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

print("Best Parameters:", best_params)

y_pred = best_model.predict(X_test)

rounded_pred = np.round(y_pred)
rounded_true = np.round(y_test.to_numpy())

temp_acc = accuracy_score(rounded_true[:, 0], rounded_pred[:, 0])
rain_acc = accuracy_score(rounded_true[:, 1], rounded_pred[:, 1])

accuracy = (temp_acc + rain_acc) / 2

X_result.head(), y_result.head(), accuracy

Fitting 3 folds for each of 18 candidates, totalling 54 fits
Best Parameters: {'estimator__max_depth': 10, 'estimator__min_samples_split': 5, 'estimator__n_estimators': 50}

(   is_explicit  danceability  energy  loudness  speechiness  acousticness  \
 0            1         0.894   0.725    -4.984       0.0432       0.00434
 1            0         0.631   0.822    -4.793       0.0269       0.21300
 2            0         0.770   0.677    -6.427       0.0589       0.52600
 3            0         0.711   0.809    -4.389       0.0955       0.04470
 4            0         0.633   0.607    -6.182       0.0532       0.18300

    instrumentalness  liveness  valence    tempo
 0          0.000012    0.0815    0.838  116.988
 1          0.001010    0.2120    0.879  149.886
 2          0.000483    0.1280    0.942  135.982
 3          0.000000    0.3390    0.816  106.017
 4          0.000001    0.1670    0.363   74.029  ,
    average_temp       rain
 0     33.503510  15.039359
 1     28.568992   1.630439
 2     28.512308   1.589733
 3     28.801291   1.109780
 4     28.410122   1.166777,
 0.14977307110438728)